services:
  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_ROOT_PASSWORD: 9xz3jrd8wf
      POSTGRES_DATABASE: takhir_db
      POSTGRES_USER: takhir_user
      POSTGRES_PASSWORD: 9xz3jrd8wf
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:7.4.0-alpine3.20
    ports:
      - "4000:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
