services:
  traefik:
    image: traefik:v3.3.2
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - --entrypoints.websecure.address=:443
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=mohammadne.dev@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"       # Temporarily expose HTTP for redirection
      - "443:443"     # HTTPS
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    networks:
      - internal

  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_ROOT_PASSWORD: 9xz3jrd8wf
      POSTGRES_DATABASE: zanbil_db
      POSTGRES_USER: zanbil_user
      POSTGRES_PASSWORD: 9xz3jrd8wf
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:7.4.0-alpine3.20
    volumes:
      - redis_data:/data
    networks:
      - internal

  zanbil:
    image: ghcr.io/mohammadne/zanbil:v0.0.1
    restart: unless-stopped
    command:
      - --environment=prod
    environment:
      ZANBIL_POSTGRES_HOST: postgres
      ZANBIL_POSTGRES_PORT: 5432
      ZANBIL_POSTGRES_USER: zanbil_user
      ZANBIL_POSTGRES_PASSWORD: 9xz3jrd8wf
      ZANBIL_POSTGRES_DATABASE: zanbil_db
      ZANBIL_REDIS_ADDRESS: redis:6379
      ZANBIL_REDIS_USERNAME: 
      ZANBIL_REDIS_PASSWORD: 
      ZANBIL_REDIS_DB: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zanbil.rule=Host(`zanbil.mohammadne.ir`)"
      - "traefik.http.routers.zanbil.entrypoints=websecure"
      - "traefik.http.routers.zanbil.tls.certresolver=myresolver"
      - "traefik.http.services.zanbil.loadbalancer.server.port=8088"
    depends_on:
      - postgres
      - redis
    networks:
      - internal

volumes:
  postgres_data:
  redis_data:

networks:
  internal:
    driver: bridge
