services:
  postgres:
    image: postgres:16.4-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: takhir_db
      POSTGRES_USER: takhir_user
      POSTGRES_PASSWORD: 9xz3jrd8wf
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0-alpine3.20
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
