CREATE TABLE IF NOT EXISTS ratings (
    id SERIAL PRIMARY KEY,
    item_id INTEGER NOT NULL, FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    rating INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

