---
logger:
  development: true
  level: "info"
  encoding: "console"
tcp:
  secure_port: 8443
  insecure_port: 8080
  tls:
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIBDDCBvwIUE1KUKVQPoywtsK8ObDt8zu3fTT4wBQYDK2VwMCkxCzAJBgNVBAYT
      AklSMRowGAYDVQQDDBF3d3cubW9oYW1tYWRuZS5pcjAeFw0yNDA0MTMxNTQ1MTFa
      Fw0yNjAzMTQxNTQ1MTFaMCkxCzAJBgNVBAYTAklSMRowGAYDVQQDDBF3d3cubW9o
      YW1tYWRuZS5pcjAqMAUGAytlcAMhAPI/RKajnuRBq1/ERE2KFzcoadIKEVCLbnMG
      PT8bJ59wMAUGAytlcANBAB1kwicnCs076aFTjeuvtgD5Pa7S5CeclsjYc0mMgZjm
      ++eJQSM7WNtTUQMtU9wjNFO/iBzN66PIZNYsG7xKCwk=
      -----END CERTIFICATE-----
    private_key: |
      -----BEGIN PRIVATE KEY-----
      MC4CAQAwBQYDK2VwBCIEINlKyJu4sFueAAY4aC9tGH9fWDpkvz+T8JojB+Nvv/Mw
      -----END PRIVATE KEY-----
