name: test

on:
  - push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: make codecov-test
      - uses: codecov/codecov-action@v5
        with:
          files: coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: mohammadne/takhir
